[package]
name = "arknights_unpack_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
lz4_flex = "0.9.5"
num_enum = "0.5.7"
serde_json = "1.0.91"
serde = { version = "1.0.152", features = ["derive"] }
bytes = "1.3.0"
